In [105]:
%run "../../../common/0_notebooks_base_setup.py"
from dhtest import test_1_numpy

/media/paulati/Nuevo vol/paula/dh/2021/dsad_2021_paula/common
default checking
Running command `conda list`... ok
jupyterlab=2.2.6 already installed
pandas=1.1.5 already installed
bokeh=2.2.3 already installed
seaborn=0.11.0 already installed
matplotlib=3.3.2 already installed
ipywidgets=7.5.1 already installed
pytest=6.2.1 already installed
chardet=4.0.0 already installed
psutil=5.7.2 already installed
scipy=1.5.2 already installed
statsmodels=0.12.1 already installed
scikit-learn=0.23.2 already installed
xlrd=2.0.1 already installed
Running command `conda install --yes nltk=3.5.0`... ok
Solving environment: ...working... done

# All requested packages already installed.


unidecode=1.1.1 already installed
pydotplus=2.0.2 already installed
pandas-datareader=0.9.0 already installed
flask=1.1.2 already installed


---

<img src='../../../common/logo_DH.png' align='left' width=35%/>


# Numpy

<a id="section_toc"></a> 
## Tabla de Contenidos

[Intro](#section_intro)

[Constructor](#section_constructor)

[Métodos para la creación de arrays](#section_metodos_creacion)

$\hspace{.5cm}$[1. empty](#section_metodos_creacion_empty)

$\hspace{.5cm}$[2. zeros](#section_metodos_creacion_zeros)

$\hspace{.5cm}$[3. ones](#section_metodos_creacion_ones)

$\hspace{.5cm}$[4. random](#section_metodos_creacion_normal)

[Atributos](#section_atributos)

$\hspace{.5cm}$[1. ndim](#section_atributos_ndim)

$\hspace{.5cm}$[2. shape](#section_atributos_shape)

$\hspace{.5cm}$[3. size]("#section_atributos_size)

$\hspace{.5cm}$[4. dtype](#section_atributos_dtype)

[Indexing](#section_indexing)

$\hspace{.5cm}$[1. Slicing](#section_indexing_slicing)

$\hspace{.5cm}$[2. Fancy Indexing](#section_indexing_fancy)

$\hspace{.5cm}$[3. Boolean Indexing](#section_indexing_boolean)


---


## Numpy Array


<a id="section_intro"></a> 
###  Intro
[volver a TOC](#section_toc)

Un array es una estructura de datos que permite agrupar varios valores o elementos en una única variable (un único nombre).

Los elementos de un array son todos del mismo tipo (a diferencia de las listas de Python).

Los arrays de una y dos dimensiones tienen nombres propios:

* un array unidimensional es un **vector**

* un arreglo bidimensional es una **tabla** o **matriz**

Los array de tres dimensiones o más se nombran N-dimensionales.


![Image](img/numpy.jpg)

---

<a id="section_constructor"></a> 
### Constructor
[volver a TOC](#section_toc)

#### Documentación 
https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html

La forma más sencilla de construir un array es usando el constructor con un único parámetro:
`numpy.array(object)`
donde object es una colección de elementos


Veamos un ejemplo:

In [106]:
import numpy as np

In [107]:
# Lista de python
python_list = [1, 4, 2, 5, 3]

# Arreglo (array) de enteros instanciado a partir de una lista:
my_numpy_array = np.array(python_list)

# Imprimo el numpy array creado
print(my_numpy_array)

[1 4 2 5 3]


<a id="section_metodos_creacion"></a> 
### Métodos para la creación de arrays
[volver a TOC](#section_toc)

#### Documentación 
https://docs.scipy.org/doc/numpy/reference/routines.array-creation.html

Numpy provee métodos para crear e inicializar arrays con determinadas características. 

Podemos crear arrays vacíos, de ceros, de unos, con una secuencia, de valores aleatorios, de valores que sigan determinada distribución.



A continuación vamos a ver un ejemplo de algunos de ellos.


<a id="section_metodos_creacion_empty"></a> 
#### Array vacío
[volver a TOC](#section_toc)

##### Documentación
https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty.html

Recibe como parámetros: las dimensiones del array a crear como una tupla, y el tipo de datos de sus elementos.

Devuelve un nuevo array de las dimensiones especificadas en la tupla que es el primer parámetro, **sin inicializar sus elementos**

`numpy.empty(shape, dtype=float)`

In [108]:
np.empty((2, 2), dtype=int)

array([[4620810973233133868, 4619863901012024509],
       [4615730935004399916, 4620810973233133868]])

In [109]:
np.empty((3, 1), dtype=float)

array([[5.72236907],
       [4.55122963],
       [9.85719454]])

In [110]:
np.empty((1, 3), dtype=bool)

array([[ True,  True,  True]])

<div id="caja1" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"><img src="../../../common/icons/para_seguir_pensando.png" style="align:left"/> </div>
  <div style="float:left;width: 85%;"><label>¿Qué elemento de la tupla indica la cantidad de filas? <br/> ¿Y la cantidad de columnas?</label></div>
</div>

<a id="section_metodos_creacion_zeros"></a> 
#### Array de ceros
[volver a TOC](#section_toc)

Veremos cómo instanciar un array de ceros de las dimensiones especificadas.

##### Documentación
https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros

Recibe como parámetros: las dimensiones del array a crear como una tupla, y el tipo de datos de sus elementos.

`numpy.zeros(shape, dtype=float)`

In [111]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
np.zeros((10, 2), dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [113]:
np.zeros((10, 2), dtype=str)

array([['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

<div id="caja2" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"><img src="../../../common/icons/haciendo_foco.png" style="align:left"/> </div>
  <div style="float:left;width: 85%;"><label>Observen las diferencias en los resultados de las dos últimas instrucciones, donde sólo cambiamos el tipo de datos de los elementos del array.</label></div>
</div>

<div id="caja3" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"><img src="../../../common/icons/bonus_track.png" style="align:left"/> </div>
  <div style="float:left;width: 85%;"><label> 
      <b>Opcional - Data type objects (dtype)</b><br/>
      https://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html<br/>
      Un objeto data type (una instancia de la clase numpy.dtype) describe cómo deben interpretarse los bytes en el bloque de memoria de tamaño fijo que corresponde al item de un array<br/>
<b>¿Qué significa dtype='&lt;U1'?</b>      
      </label></div>
</div>

Instanciamos un objeto dtype:

In [114]:
dt_array_item = np.dtype('<U1')

Con `dt_array_item.type` vemos el tipo usado para instanciar a dt_array_item

In [115]:
dt_array_item.type

numpy.str_

Entonces, dtype='<U1' nos indica que los items del array resultado son de tipo numpy.str_ (cadena de caracteres)

<a id="section_metodos_creacion_ones"></a> 
#### Array de unos
[volver a TOC](#section_toc)

Ahora veremos cómo instanciar un array de unos de las dimensiones especificadas.

##### Documentación
https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html

Recibe como parámetros: las dimensiones del array a crear como una tupla, y el tipo de datos de sus elementos.

`numpy.ones(shape, dtype=float)`

In [116]:
np.ones((10, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [117]:
np.ones((10, 2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [118]:
np.ones((10, 2), dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

<div id="caja4" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"><img src="../../../common/icons/haciendo_foco.png" style="align:left"/> </div>
  <div style="float:left;width: 85%;"><label>Observen las diferencias en los tres resultados, donde sólo cambiamos el tipo de datos de los elementos del array.</label></div>
</div>


<a id="section_metodos_creacion_normal"></a> 
#### Array de valores aleatorios con distribución normal
[volver a TOC](#section_toc)

Ahora veremos cómo instanciar un array de números aleatorios que siga una distribución normal

##### Documentación
https://docs.scipy.org/doc/numpy/reference/random/index.html

https://docs.scipy.org/doc/numpy/reference/random/generator.html

https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.Generator.normal.html#numpy.random.Generator.normal

El método que genera números aleatorios con distribución normal recibe como parámetros: la media, el desvio standard y las dimensiones del array de salida

`Generator.normal(loc=0.0, scale=1.0, size=None)`

Instanciamos una instancia default de Generator:

In [119]:
random_generator = np.random.default_rng()

Generamos ahora 12 números con distribución normal de media 0 y desvío standard 1:

In [120]:
random_generator.normal(loc = 0, scale = 1, size = 12)

array([ 0.90386291, -0.38863153, -1.02598414, -0.71116501, -1.89875443,
       -2.14411554,  0.83285234,  0.0444769 , -0.37362976,  0.19186963,
        0.62263422, -0.59662803])

Ahora generamos una matriz de 16 filas y 4 columnas con números con distribución normal de media 0 y desvío standard 1:

In [121]:
 random_generator.normal(0, 1, size = (16,4))

array([[ 1.06949863e+00, -6.14457573e-01, -1.66673432e-01,
         1.07568803e+00],
       [ 6.23021082e-01,  4.14716141e-01, -5.11288824e-01,
        -1.53575735e+00],
       [ 1.19521068e+00, -4.14345490e-01,  5.89863906e-01,
        -1.71584630e+00],
       [ 1.12222524e-01, -2.44364016e-01,  3.67180254e-01,
        -1.14003102e+00],
       [ 2.19979356e-01, -1.86961816e+00,  1.19250801e-01,
         1.52702508e-01],
       [-1.25313310e+00, -8.39831992e-01,  2.92962576e-04,
         7.24818145e-01],
       [ 8.12321806e-01, -1.70707393e+00,  1.44462674e+00,
         1.28997590e+00],
       [-1.46423676e+00,  1.14580014e+00, -3.31215728e-01,
        -1.09759943e+00],
       [ 2.29428982e-01, -1.08883308e+00, -1.46258114e+00,
        -1.14897121e+00],
       [ 2.04679686e+00, -8.79507395e-01,  8.76389457e-01,
        -1.03353780e+00],
       [-4.56198805e-01,  5.69354949e-01, -1.31342009e-01,
        -8.59428132e-01],
       [-2.45902409e-01, -5.44746764e-01, -2.51896050e-01,
      

Observen que cada vez que ejecutamos esta linea `random_generator.normal(loc = 0, scale = 1, size = 12)` obtenemos valores diferentes para los elementos del array.

Prueben ejecutarla tres o cuatro veces...

Lo mismo ocurre con `random_generator.normal(0, 1, size = (16,4))`

Si queremos obtener el mismo resultado en todas las ejecuciones, debemos inicializar la semilla del generador de números aleatorios.

Para eso hacemos inicializamos la instancia de `Generator` con una semilla cualquiera pero fija:

In [122]:
seed_cualquier_numero = 2843
random_generator_seed = np.random.default_rng(seed_cualquier_numero)

Y ahora ejecutemos varias veces las mismas lineas que probamos arriba, usando el objeto random_generator_seed inicializado con una semilla determinada:

In [123]:
random_generator_seed = np.random.default_rng(seed_cualquier_numero)
random_generator_seed.normal(loc = 0, scale = 1, size = 12)

array([ 0.770969  ,  0.33288743, -0.7145752 ,  0.05428423, -1.44839055,
        0.05562249,  0.04235933, -1.06432701,  3.23668651, -2.61427606,
        0.17057975, -0.11374496])

In [124]:
random_generator_seed = np.random.default_rng(seed_cualquier_numero)
random_generator_seed.normal(0, 1, size = (16,4))

array([[ 0.770969  ,  0.33288743, -0.7145752 ,  0.05428423],
       [-1.44839055,  0.05562249,  0.04235933, -1.06432701],
       [ 3.23668651, -2.61427606,  0.17057975, -0.11374496],
       [ 1.5431114 , -0.2433953 ,  0.54422367,  0.83475881],
       [ 0.04301992, -0.63558257, -0.16046816,  1.64470349],
       [ 1.33297402, -0.99626982, -1.29590249, -0.61893616],
       [-0.22066461,  0.22727611, -1.38125624,  0.04929038],
       [ 0.63748133, -0.19561326,  0.5938797 ,  1.53733473],
       [-0.27605803,  0.16768242,  0.44111193, -0.07839599],
       [ 0.98677009,  0.94900021, -1.19024724, -0.91697433],
       [-0.62741927,  2.1939412 , -1.0684962 , -1.79228955],
       [ 1.07398541,  1.96988692,  0.3815075 , -0.52205868],
       [ 1.33797156, -0.65238485, -0.74753246,  0.20865684],
       [ 0.99353863,  1.16058088,  1.36554724,  0.07186766],
       [ 1.79045939, -2.00201905, -0.5718638 ,  0.69506072],
       [-0.06683168, -0.74753465, -0.7760167 ,  0.4493421 ]])

¿Notaron que ahora **no cambia** el resultado en cada ejecucuión?

<div id="caja5" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"><img src="../../../common/icons/ponete_a_prueba.png" style="align:left"/> </div>
  <div style="float:left;width: 85%;"><label>
      <b>Ejercicio 1</b>
    
Usando como semilla el numero 2843, construyan un objeto array de Numpy con 500 números aleatorios de distribución binomial con n = 100 y p = 0.7
    
Ayuda: https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.Generator.binomial.html#numpy.random.Generator.binomial
      
Completen el código de la función random_binomial():</label></div>
</div>

In [125]:
import numpy as np

def random_binomial():
    
    # cambiar aquí:
    #result = np.array([1,2,3])
    #result = [1, 2, 3]
    result = []
    
    return(result)

resultado = random_binomial()
test_1_numpy.test_random_binomial(resultado)




'El tipo devuelto es incorrecto. El resultado debe ser un array ndimensional de Numpy (numpy.ndarray).'

<a id="section_atributos"></a> 
### Atributos
[volver a TOC](#section_toc)

#### Documentación

https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#array-attributes

Vamos a ver ahora ejemplos de atributos de un array de tres dimensiones, con numeros aleatorios de distribución uniforme de tamaño 3 * 4 * 5

Generador de números aleatorios con distribución uniforme:

https://docs.scipy.org/doc/numpy/reference/random/generated/numpy.random.Generator.uniform.html#numpy.random.Generator.uniform

In [126]:
random_generator_seed = np.random.default_rng(seed_cualquier_numero)
low = 10 #incluye el limite inferior
high = 50 # no incluye el límite superior
size = (3, 4, 5)
array_3D = random_generator_seed.uniform(low, high, size)
array_3D

array([[[32.88947629, 16.94855803, 42.83670351, 30.25105684,
         28.20491852],
        [25.18521523, 40.18344021, 34.34396248, 49.42877817,
         25.9067247 ],
        [49.96435545, 39.05367532, 25.72967186, 40.81169652,
         14.0724828 ],
        [41.55501295, 21.67492545, 22.49339028, 25.49163559,
         26.50349253]],

       [[40.72705982, 28.63930892, 18.02914832, 27.35671068,
         38.97125442],
        [16.66917961, 46.25005127, 30.72094445, 48.47205286,
         15.6034732 ],
        [11.79424167, 40.67551164, 21.90868009, 19.00439909,
         23.67958317],
        [10.55338987, 35.92638548, 15.26580613, 12.67264131,
         37.95862821]],

       [[24.33023875, 49.46354377, 48.15236324, 14.74696516,
         23.94498762],
        [19.34227574, 12.22724432, 13.35657914, 42.88661071,
         26.11646608],
        [29.62041973, 17.17235157, 36.46619752, 31.23546738,
         17.94252221],
        [38.58722823, 19.18467869, 35.2361267 , 34.25595785,
         28

<a id="section_atributos_ndim"></a> 
#### ndim
[volver a TOC](#section_toc)

Cantidad de dimensiones del array

In [127]:
array_3D.ndim

3

<a id="section_atributos_shape"></a> 
#### shape
[volver a TOC](#section_toc)

Tupla con las dimensiones del array

In [128]:
array_3D.shape

(3, 4, 5)

In [129]:
type(array_3D.shape)

tuple

> Observación: `len(array_3D.shape) == array_3D.ndim`

<a id="section_atributos_size"></a> 
#### size
[volver a TOC](#section_toc)

Cantidad de elementos en el array

In [130]:
array_3D.size

60

> Observación: `np.prod(array_3D.shape) == array_3D.size`
>
> `np.prod` multiplica todos los elementos en la tupla

<a id="section_atributos_dtype"></a> 
#### dtype
[volver a TOC](#section_toc)

Tipo de datos de los elementos que componen el array

In [131]:
array_3D.dtype

dtype('float64')

<a id="section_indexing"></a> 
### Indexing
[volver a TOC](#section_toc)

Un problema común es seleccionar los elementos de un array de acuerdo a algún criterio. 

Llamamos "indexing" a la operación que resuelve el problema de acceder a los elementos de un array con algún criterio. 

Existen tres tipos de indexing en Numpy:

* **Array Slicing**: accedemos a los elementos con los parámetros start,stop,step. 
Por ejemplo `my_array[0:5:-1]`

* **Fancy Indexing**: creamos una lista de índices y la usamos para acceder a ciertos elementos del array:  `my_array[[3,5,7,8]]`

* **Boolean Indexing**: creamos una "máscara booleana" (un array o lista de True y False) para acceder a ciertos elementos: `my_array[my_array > 4]`


<a id="section_indexing_slicing"></a>
#### Array Slicing 
[volver a TOC](#section_toc)

##### Slicing sobre una dimensión

El slicing es similar al de las listas de python [start:stop:step]. 

El índice stop no se incluye pero el start sí se incluye. 

Por ejemplo [1:3] incluye al índice 1 pero no al 3.

Funciona como un intervalo semicerrado [1,3).

Si necesitan refrescar cómo funciona el slicing en listas pueden ver https://stackoverflow.com/questions/509211/understanding-slice-notation


![Image](img/numpy_indexing.jpg)



Veamos algunos ejemplo:

Creamos un array de una dimensión usando el método
`np.arange` que devuelve valores espaciados uniformemente dentro de un intervalo dado.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html

In [132]:
# Sobre un array de una dimension con números enteros entre 0 y 9:
one_d_array = np.arange(10)
one_d_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
# Start = 1:  empezamos por el segundo elemento
# Stop: No está definido, entonces llegamos hasta el final.
# Step: El paso o distancia entre los elementos es 2.
one_d_array[1::2]  

array([1, 3, 5, 7, 9])

In [134]:
# Start: No está definido, entonces comenzamos desde el primero.
# Stop: No está definido, entonces llegamos hasta el final.
# Step = -1, para invertir el orden del array
one_d_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [135]:
# Si queremos hacer slicing en orden invertido
one_d_array[7:2:-1]  

array([7, 6, 5, 4, 3])

##### Slicing sobre arrays de más  dimensiones

Cuando tenemos más de una dimensión, podemos hacer slicing sobre cada una de ellas separándolas con una coma. 

Veamos algunos ejemplos:

In [136]:
random_generator_seed = np.random.default_rng(seed_cualquier_numero)
low = 0 #incluye el limite inferior
high = 10 # no incluye el límite superior
size = (3, 4)
two_d_array = random_generator_seed.uniform(low, high, size)
two_d_array

array([[5.72236907, 1.73713951, 8.20917588, 5.06276421],
       [4.55122963, 3.79630381, 7.54586005, 6.08599062],
       [9.85719454, 3.97668117, 9.99108886, 7.26341883]])

In [137]:
# Los dos puntos ( : ) indican que accedemos a todos los elementos de cada fila 
# y el cero después de la coma indica que sólamente lo hacemos para la columna 0 (la primera).
two_d_array[:, 0]

array([5.72236907, 4.55122963, 9.85719454])

In [138]:
# Accedemos a la tercer fila
two_d_array[2, :]

array([9.85719454, 3.97668117, 9.99108886, 7.26341883])

In [139]:
# Otra forma de acceder a la tercer fila
two_d_array[2]

array([9.85719454, 3.97668117, 9.99108886, 7.26341883])

In [140]:
# Todas la filas, un slice de la segunda y tercer columna (índices 1 y 2)
two_d_array[:, 1:3]

array([[1.73713951, 8.20917588],
       [3.79630381, 7.54586005],
       [3.97668117, 9.99108886]])

In [141]:
# todas las filas, todas las columnas listadas en orden inverso
two_d_array[:, ::-1]

array([[5.06276421, 8.20917588, 1.73713951, 5.72236907],
       [6.08599062, 7.54586005, 3.79630381, 4.55122963],
       [7.26341883, 9.99108886, 3.97668117, 9.85719454]])


<a id="section_indexing_fancy"></a> 
#### Fancy Indexing
[volver a TOC](#section_toc)

Esta técnica consiste en generar listas que contienen los índices de los elementos que queremos seleccionar y utilizar estas listas para indexar.

Veamos algunos ejemplos:

In [142]:
# nos quedamos con todas las columnas y las filas 1, 3, 2 y repetimos la 1 (índices 0,2,1,0)
lista_indices_filas = [0, 2, 1, 0]
two_d_array[lista_indices_filas]

array([[5.72236907, 1.73713951, 8.20917588, 5.06276421],
       [9.85719454, 3.97668117, 9.99108886, 7.26341883],
       [4.55122963, 3.79630381, 7.54586005, 6.08599062],
       [5.72236907, 1.73713951, 8.20917588, 5.06276421]])

In [143]:
# nos quedamos con todas las filas y las columnas 3, 4, 2, y reptimos la 3 (índices 2,3,1,2)
lista_indices_columnas = [2, 3, 1, 2]
two_d_array[:, lista_indices_columnas]

array([[8.20917588, 5.06276421, 1.73713951, 8.20917588],
       [7.54586005, 6.08599062, 3.79630381, 7.54586005],
       [9.99108886, 7.26341883, 3.97668117, 9.99108886]])

In [144]:
# y ahora seleccionamos tanto filas como columnas, combinando los dos casos anteriores
two_d_array[lista_indices_filas, lista_indices_columnas]

array([8.20917588, 7.26341883, 3.79630381, 8.20917588])

Observemos que al pasar las dos listas, estamos seleccionando los elementos
(0, 2), (2, 3), (1, 1) y (0,2)

Se cumple que `indice_elem_i = (lista_indices_filas[i], lista_indices_columnas[i])`

<a id="section_indexing_boolean"></a> 
#### Boolean Indexing
[volver a TOC](#section_toc)

Esta técnica se basa en crear una "máscara booleana", que es una lista de valores True y False que sirve para seleccionar sólo los elementos cuyo índice coincide con un valor True.  

Veamos algunos ejemplos sobre two_d_array:

In [145]:
two_d_array

array([[5.72236907, 1.73713951, 8.20917588, 5.06276421],
       [4.55122963, 3.79630381, 7.54586005, 6.08599062],
       [9.85719454, 3.97668117, 9.99108886, 7.26341883]])

Vamos a seleccionar los elementos que sean mayores que 5. Para esos creamos uma máscara con esa condición:

In [146]:
mask_great_5 = two_d_array > 5
mask_great_5

array([[ True, False,  True,  True],
       [False, False,  True,  True],
       [ True, False,  True,  True]])

La máscara tiene valor True en aquellos elementos de two_d_array con valor mayor a 5, y False en los que tienen valor menor o igual que 5.

Ahora usemos esa máscara para seleccionar los elementos que cumplen esa condición, o sea los que tienen valor True en la máscara:

In [147]:
two_d_array[mask_great_5]

array([5.72236907, 8.20917588, 5.06276421, 7.54586005, 6.08599062,
       9.85719454, 9.99108886, 7.26341883])

Definamos ahora una condición más compleja: vamos a seleccionar los elementos que sean mayores que 5 y menores que 8

In [148]:
mask_great_5_less_8 = (two_d_array > 5) & (two_d_array < 8)
mask_great_5_less_8

array([[ True, False, False,  True],
       [False, False,  True,  True],
       [False, False, False,  True]])

Ahora usemos esa máscara para seleccionar los elementos que cumplen esa condición, o sea los que tienen valor True en la máscara:

In [149]:
two_d_array[mask_great_5_less_8]

array([5.72236907, 5.06276421, 7.54586005, 6.08599062, 7.26341883])

<div id="caja6" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"><img src="../../../common/icons/en_resumen.png" style="align:left"/> </div>
  <div style="float:left;width: 85%;"><label>Como podemos ver, la dificultad de la selección está en la definición de la máscara, que puede llegar a ser bastante compleja. Pero una vez que está calculada, el filtro es idéntico independientemente de la cantidad de condiciones que están involucradas en su definición, y la dimensión del array a filtar.</label></div>
</div>

<div id="caja10" style="float:left;width: 100%;">
  <div style="float:left;width: 15%;"><img src="../../../common/icons/ponete_a_prueba.png" style="align:left"/> </div>
  <div style="float:left;width: 85%;"><label>





<b>Ejercicio 2</b>

Tenemos un dataset que representa la cantidad de precipitaciones del 2014 en la ciudad de Seattle

La cantidad de precipitaciones está en la **cuarta** columna, completa el código de una función que reciba el dataset y devuelva estos valores.
    
Queremos saber la cantidad de días:
* sin lluvia: valor de precipitaciones es 0
* con lluvia: valor de precipitaciones es distinto de 0
* con más de 100 de lluvia: valor de precipitaciones es mayor a 100
* con lluvia, pero no mayor a 100: valor de precipitaciones es distinto de 0 y menor o igual a 100 
   
</label></div>    
</div>

In [150]:
def precipitaciones(data):
    # modificar aquí:
    result = None
    return result

def cant_dias_sin_lluvia(precip):
    # cambiar aquí:
    result = 7
    return result

def cant_dias_con_lluvia(precip):
    # cambiar aquí:
    result = 7
    return result

def cant_dias_con_lluvia_mayor_100(precip):
    # cambiar aquí:
    result = 7
    return result

def cant_dias_con_lluvia_menorigual_100(precip):
    # cambiar aquí:
    result = 7
    return result

import numpy as np
import os.path

data_location = os.path.abspath('../Data/Seattle2014.csv')
data = np.genfromtxt(data_location, skip_header=1, delimiter=',')
data

valores_precipitaciones = precipitaciones(data)

In [151]:
test_1_numpy.test_precipitaciones(valores_precipitaciones)

'El tipo devuelto es incorrecto. El resultado debe ser un array ndimensional de Numpy (numpy.ndarray).'

In [152]:
sin_lluvia = cant_dias_sin_lluvia(valores_precipitaciones)
test_1_numpy.test_cant_dias_sin_lluvia(sin_lluvia)

'La respuesta es incorrecta, revisá cómo escribiste la máscara booleana'

In [153]:
con_lluvia = cant_dias_con_lluvia(valores_precipitaciones)
test_1_numpy.test_cant_dias_con_lluvia(con_lluvia)

'La respuesta es incorrecta, revisá cómo escribiste la máscara booleana'

In [154]:
con_lluvia_mayor_100 = cant_dias_con_lluvia_mayor_100(valores_precipitaciones)
test_1_numpy.test_cant_dias_con_lluvia_mayor_100(con_lluvia_mayor_100)

'La respuesta es incorrecta, revisá cómo escribiste la máscara booleana'

In [155]:
con_lluvia_menorigual_100 = cant_dias_con_lluvia_menorigual_100(valores_precipitaciones)
test_1_numpy.test_cant_dias_con_lluvia_menorigual_100(con_lluvia_menorigual_100)

'La respuesta es incorrecta, revisá cómo escribiste la máscara booleana'

___

## Versiones

In [156]:
import numpy
numpy.version.version

'1.19.2'