In [2]:
%run "../../../common/0_notebooks_base_setup.py"    

/media/paulati/Nuevo vol/paula/dh/2021/dsad_2021_paula/common
default checking
Running command `conda list`... ok
jupyterlab=2.2.6 already installed
pandas=1.1.5 already installed
bokeh=2.2.3 already installed
seaborn=0.11.0 already installed
matplotlib=3.3.2 already installed
ipywidgets=7.5.1 already installed
pytest=6.2.1 already installed
chardet=4.0.0 already installed
psutil=5.7.2 already installed
scipy=1.5.2 already installed
statsmodels=0.12.1 already installed
scikit-learn=0.23.2 already installed
xlrd=2.0.1 already installed
Running command `conda install --yes nltk=3.5.0`... ok
Solving environment: ...working... done

# All requested packages already installed.


unidecode=1.1.1 already installed
pydotplus=2.0.2 already installed
pandas-datareader=0.9.0 already installed
flask=1.1.2 already installed


---

<img src='../../../common/logo_DH.png' align='left' width=35%/>


La idea de esta práctica es ejercitar los puntos que vamos a necesitar para resolver el desafío.

Usaremos un resumen del dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data


## Ejercicio 1
Leer los datos del archivo /M1/CLASE_03_Numpy/Data/sales_data_sample_excercise.csv

Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres. 

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.

¿Qué pasaría si intentáramos crear una instancia de tipo int? ¿Y de tipo float?


In [3]:
import numpy as np

# local:
data_location = '../Data/sales_data_sample_excercise.csv'


In [4]:
data_type_default = np.genfromtxt(data_location, skip_header=1, delimiter='\t')
data_type_default

array([[1.01070e+04, 2.87100e+03, 2.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01210e+04, 2.76590e+03, 5.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01340e+04, 3.88434e+03, 7.00000e+00, 2.00300e+03,         nan,
                nan],
       ...,
       [1.03860e+04, 5.41757e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.03970e+04, 2.11616e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.04140e+04, 3.07944e+03, 5.00000e+00, 2.00500e+03,         nan,
                nan]])

In [5]:
data_type_str = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= str)
data_type_str

array([['10107', '2871', '2', '2003', 'Motorcycles', 'USA'],
       ['10121', '2765.9', '5', '2003', 'Motorcycles', 'France'],
       ['10134', '3884.34', '7', '2003', 'Motorcycles', 'France'],
       ...,
       ['10386', '5417.57', '3', '2005', 'Ships', 'Spain'],
       ['10397', '2116.16', '3', '2005', 'Ships', 'France'],
       ['10414', '3079.44', '5', '2005', 'Ships', 'USA']], dtype='<U16')

In [6]:
data_type_int = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= int)
data_type_int

array([[10107,  2871,     2,  2003,    -1,    -1],
       [10121,    -1,     5,  2003,    -1,    -1],
       [10134,    -1,     7,  2003,    -1,    -1],
       ...,
       [10386,    -1,     3,  2005,    -1,    -1],
       [10397,    -1,     3,  2005,    -1,    -1],
       [10414,    -1,     5,  2005,    -1,    -1]])

In [7]:
data_type_float = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= float)
data_type_float

array([[1.01070e+04, 2.87100e+03, 2.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01210e+04, 2.76590e+03, 5.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01340e+04, 3.88434e+03, 7.00000e+00, 2.00300e+03,         nan,
                nan],
       ...,
       [1.03860e+04, 5.41757e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.03970e+04, 2.11616e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.04140e+04, 3.07944e+03, 5.00000e+00, 2.00500e+03,         nan,
                nan]])

# Ejercicio 2 - Tipos

Crear un array numérico que tenga como valores las columna SALES y otro array de str que tenga como valores la columna COUNTRY

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

In [8]:
data = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= str)

sales_vector_str = data[:, 1]
sales_vector =  sales_vector_str.astype(np.float)
print(sales_vector)

country_vector = data[:, 5]
print(country_vector)


[2871.   2765.9  3884.34 ... 5417.57 2116.16 3079.44]
['USA' 'France' 'France' ... 'Spain' 'France' 'USA']


In [9]:
sales_vector_str

array(['2871', '2765.9', '3884.34', ..., '5417.57', '2116.16', '3079.44'],
      dtype='<U16')

## Ejercicio 3 - Funciones de agregación

Sobre los datos de precios de ventas (columna SALES) calcular:

* mínimo

* máximo

* promedio

* cantidad

* suma

Ayuda: https://docs.scipy.org/doc/numpy-1.17.0/reference/routines.statistics.html

In [10]:
np.min(sales_vector)

482.13

In [11]:
np.max(sales_vector)

14082.8

In [12]:
np.average(sales_vector)

3553.889071909316

In [13]:
sales_vector.size

2823

In [14]:
np.sum(sales_vector)

10032628.85

## Ejercicio 4 - Indexing

a) ¿Cuántas ventas se hicieron en USA?

Ayuda: boolean indexing

b) ¿Cuáles son los precios de las 5 ventas que están en las filas 6 a 10 del dataset?

Resolvamos usando array slicing y fancy indexing

Ayuda: recuerden `range` https://docs.python.org/3/library/functions.html#func-range

In [15]:
print(country_vector)
mask = country_vector == 'USA'
print(mask)
country_vector_USA = country_vector[mask]
country_vector_USA.size


['USA' 'France' 'France' ... 'Spain' 'France' 'USA']
[ True False False ... False False  True]


1004

In [16]:
# array slicing:
sales_vector_slicing = sales_vector[6:11]
# observemos que el límite superior no está incluído
print(sales_vector_slicing)

[2497.77 5512.32 2168.54 4708.44 3965.66]


In [17]:
# fancy indexing

indexes = range(6, 11, 1)
indexes_int = [6, 7, 8, 9, 10]
sales_vector_fancy = sales_vector[indexes_int]
print(sales_vector_fancy)


[2497.77 5512.32 2168.54 4708.44 3965.66]


In [18]:
# veo que obtengo el mismo resultado con una u otra forma de indexación:

# una forma es comparar elemento a elemento los dos arrays:
print(sales_vector_slicing == sales_vector_fancy)

# otra forma es ver si la cantidad de elementos que son iguales en los dos arrays (sum(sales_vector_slicing == sales_vector_fancy)) 
# es igual a la cantidad total de elementos por array
cant_elem = len(sales_vector_slicing)
print(sum(sales_vector_slicing == sales_vector_fancy) == cant_elem)

# y otra forma es ver si ningún elemento distinto, o sea negar any:
print(not any(sales_vector_slicing != sales_vector_fancy))

[ True  True  True  True  True]
True
True
